[options]
; /mnt/modules je tento repozitar. Kazdy projekt ma vlastni slozku s moduly,
; kazdou takovou slozku je potreba uvest v addons_path.
addons_path = /mnt/modules,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
; heslo pro spravu databazi, zmente pred nasazenim
admin_passwd = zmente-me
